config/routes.rb
Dbhiv::Application.routes.draw do
   
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  resources :questions, except: [:new] do
    resources :answers, only: [:create]
  end
  
  match '/register', to: 'users#new', via: :get
  match 'login', to: 'sessions#new', via: :get
  match 'logout', to: 'sessions#destroy', via: :delete

  match '/your_questions', to: 'questions#your_questions', via: :get
  match '/search', to: 'questions#search', via: :get
  root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :body, presence: true, length: {in: 2..255}
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :body, presence: true, length: {in: 5..255}
  validates :solved, inclusion: {in: [true, false]}

	def self.unsolved(params)
		where(solved: false).paginate(page: params[:page], order: 'created_at DESC', per_page: 5)
	end  

	def self.search(params)
		where("body LIKE ?", "%#{params[:keyword]}%").paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :questions
	has_many :answers

	validates :username, presence: true, uniqueness: {case_sensitive: false},
				length: {in: 4..12},
				format: { with: /^[a-z][a-z0-9]*$/, multiline: true, message: "Can only contain lowercase letters and numbers"}
	validates :password, length:{in: 4..80}	
	validates :password_confirmation, length: {in: 4..80}

	def your_questions(params)
		questions.paginate(page: params[:page], order: 'created_at DESC', per_page: 3)
	end		
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	before_filter :auth, only: [:create]
	def create
		@question = Question.find(params[:question_id])
		@answer = @question.answers.build(answer_params)
		@answer.user = current_user

		if @answer.save
			flash[:success] = "Your answer has been posted"
			redirect_to @question
		else
			@question = Question.find(params[:question_id])
			render 'questions/show'
		end
	end

	private

  def answer_params
      params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method [:current_user, :logged_in?]
  protected

  def login(user)
    session[:user_id] = user.id
  end
  
  def current_user
  	current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!current_user.nil?
  end

  def auth
    redirect_to login_url, alert: "You must login to access that page" unless logged_in?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :auth, only: [:create, :your_questions, :edit, :update]
  
  def index
  	@question = Question.new
    @questions = Question.unsolved(params)
  end

  def create
  	@question = current_user.questions.build(question_params)

  	if @question.save
  		flash[:success] = "Your question has been posted!"
  		redirect_to @question
  	else
      @questions = Question.unsolved(params)
  		render "index"
  	end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = current_user.questions.find(params[:id])
  
    if @question.update_attributes(question_params)
      flash[:success] = "Your question has been updated"
      redirect_to @question
    else
      render 'edit'
    end
  end

  def your_questions
    @questions = current_user.your_questions(params)
  end

  def search
    @questions = Question.search(params)
  end

  private

  def question_params
      params.require(:question).permit(:body, :solved)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:session][:username])

  	if user && user.authenticate(params[:session][:password])
  		login user
  		flash[:success] = "You are now logged in"
  		redirect_to root_url
  	else
  		flash.now[:error] = "Incorrect username/password combination"
  		render 'new'
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You are now logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      login @user
  		flash[:success] = "Thanks for registering"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  private

  def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
	def on_your_questions_page?
		action_name == 'your_questions'
	end

	def display_solved(question)
		(question.solved) ? ' - (Solved) ' : ''
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<li>
	<%= answer.body %> - by <span class= "username"><%= answer.user.username.capitalize %></span> - <%= time_ago_in_words(answer.created_at) %> ago
</li>

app/views/answers/_answer_form.html.erb
<%= form_for([@question, @answer]) do |f| %>
	<%= render 'common/form_errors', object: @answer%>

	<p>
		<%= f.label :body, "Answer" %>
		<%= f.text_area :body %>
		<%= f.button "Post Answer", class: "btn btn-success" %>
	</p>
<% end %>

app/views/common/_form_errors.html.erb
<% if object.errors.any? %>
	<ul id="form-errors">
		<% object.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
	</ul>
<% end %>

app/views/common/_search_form.html.erb
<%= form_tag(search_path, method: :get) do %>
	<%= text_field_tag :keyword, "Search", size: 20 , id: 'keyword'  %>
	<%= submit_tag "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : "Dbhiv" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="brand coName" ><%= link_to "Dbhiv", questions_path%></div>
          <div class="container-fluid nav-collapse">
            
            <ul class="nav navbarcontent">
              <% if logged_in? %>
                <li class = "pull-left"><%= link_to "Your Q's", your_questions_path %></li>
                <li class = "pull-left"><%= link_to "Logout(#{current_user.username})", logout_path, method: :delete %></li>
              <% else %>
                <li class = "pull-right"><%= link_to "Register", register_path %></li>
                <li class = "pull-right"><%= link_to "Login", login_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <img src="/assets/child.jpeg" alt="childkdf">
        </div>
        <div class="span9">
          <%= bootstrap_flash %>
          <div >
              <%= render 'common/search_form' %>
            </div><!-- end searchbar -->
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class="page-footer navbar navbar-fixed-bottom">
        <div class="container">
          <ul class="social">
            <!-- <li class="social-buttons social">
              <iframe id="twitter-widget-1" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/follow_button.1384994725.html#_=1386799988348&amp;id=twitter-widget-1&amp;lang=en&amp;screen_name=twbootstrap&amp;show_count=true&amp;show_screen_name=true&amp;size=m" class="twitter-follow-button twitter-follow-button" title="Twitter Follow Button" data-twttr-rendered="true" style="width: 237px; height: 20px;"></iframe>
            </li>
            <li class="social-buttons social">
              <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/tweet_button.1384994725.html#_=1386799988336&amp;count=horizontal&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http%3A%2F%2Flocalhost%3A9001%2Fgetting-started%2F&amp;related=mdo%3ACreator%20of%20Twitter%20Bootstrap&amp;size=m&amp;text=Getting%20started%20%C2%B7%20Bootstrap&amp;url=http%3A%2F%2Fgetbootstrap.com%2F&amp;via=twbootstrap" class="twitter-share-button twitter-tweet-button twitter-count-horizontal" title="Twitter Tweet Button" data-twttr-rendered="true" style="width: 107px; height: 20px;"></iframe>
            </li> -->
          </ul>
          <p>&copy; DbHiv Company 2013</p>
        </div>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/questions/_question.html.erb
<li>
	<%= link_to truncate(question.body, length: 35), question %> by <%= question.user.username.capitalize %>

	<% if on_your_questions_page? %>
	<%= display_solved(question) %>
		- <%= link_to "Edit", edit_question_path(question) %>
	<% end %>

	- (<%= pluralize(question.answers.count, 'answer') %>) - Asked <%= time_ago_in_words(question.created_at) %> ago
</li>

app/views/questions/_question_form.html.erb
<%= form_for(@question) do |f| %>
	<%= render "common/form_errors", object: @question %>
	<p>
		<%= f.label :body, "Question" %><br >
		<%= f.text_area :body, placeholder: "Ask your question here..." %> 
		<%= f.button "Ask a question", class: "btn btn-primary" %> 
	</p>
<% end %>

app/views/questions/edit.html.erb
<% provide(:title, "Edit your Question") %>

<h1>Edit your question</h1>

<%= form_for(@question) do |f| %>

	<%= render 'common/form_errors', object: @question %>

	<p>
		<%= f.label :body, "Your question:" %><br >
		<%= f.text_field :body %>
	</p>

	<p>
		<%= f.check_box :solved , class: "checkbox"%>
		<%= f.label :solved , "Click here if your question has been solved", class: "checkbox"%>	
		
	</p>
	
	<p>
		<%= f.button "Update", class: "btn btn-success" %>
	</p>
<% end %>

app/views/questions/index.html.erb
<%= provide(:title, "DBHIV | Home" )%>
<div id="ask">
<h1>Ask a Question</h1>
	<% if logged_in? %>
		<%= render 'question_form' %>
	<% else %>
		<p>Please login to ask or answer questions</p>
	<% end %>
</div><!-- end ask -->

<div id="questions">
	<h2>Unsolved Questions</h2>
	<% if @questions.any? %>
		<ul>
			<%= render @questions %>
		</ul>
		<%= will_paginate %>
	<% else %>
		<p>No Questions have been asked</p>
	<% end %>
</div> <!-- end questions -->

app/views/questions/search.html.erb
<% provide(:title, "Search Results") %>
<h1>Search Results</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions%>
	</ul>
	<%= will_paginate %>
<% else %>
	<p>Nothing found. Please try using a different keyword</p>
<% end %>

app/views/questions/show.html.erb
<% provide(:title, "View Question") %>

<h2>
	<%= @question.user.username.capitalize %> asks:
</h2>

<p>
	<%= @question.body %>
</p>
<div id="answers">
	<h3>Answers</h3>

	<% if @question.answers.any? %>
		<ul>
			<%= render @question.answers %>
		</ul>
	<% else %>
		<p>
			This question has not been answered yet
		</p>
	<% end %>
</div> <!-- answers end -->
<div id="post-answer">
	<p>
		<h3>Answer this question</h3>

		<% if logged_in? %>
			<%= render 'answers/answer_form' %>
		<% else %>
			<p>Please login to post an answer for this question</p>
		<% end %>
	</p>
</div><!-- end post-answer -->

<div>
	<p><%= link_to "Back", questions_path %> </p>
</div>

app/views/questions/your_questions.html.erb
<%provide(:title, "Your questions") %>

<h1>Your Questions</h1>

<% if @questions.any? %>
	<ul>
		<%= render @questions %>
	</ul>
	<%=will_paginate %>
<% else %>
	<p>You have not asked a question yet</p>
<% end %>

app/views/users/new.html.erb
<%= provide(:title, "DBHIV | Register") %>

<h1>Register</h1>

<%= form_for(@user) do |f|%>
	<%= render "common/form_errors", object: @user %>

	<p>
		<%= f.label :username %> <br>
		<%= f.text_field :username %>
	</p>

	<p>
		<%= f.label :password %> <br>
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation, 'Confirm' %> <br>
		<%= f.password_field :password_confirmation %>
	</p>

	<p>
		<%= f.button "Register", class: "btn btn-primary"%>
	</p>

<% end %>